test_upper_case_names (__main__.TestExercice) ... ERROR

======================================================================
ERROR: test_upper_case_names (__main__.TestExercice)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_exercice.py", line 17, in test_upper_case_names
    output = list(map(exercice.majuscule, self.words))
  File "/home/runner/work/c03_ch2_ecriture-Eli-michaud/c03_ch2_ecriture-Eli-michaud/exercice.py", line 7, in majuscule
    resultat += char(ord(lettre)-32)
NameError: name 'char' is not defined

----------------------------------------------------------------------
Ran 1 test in 0.000s

FAILED (errors=1)
